inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

require:
  - ./lib/statsd/instrument/rubocop/metric_return_value.rb
  - ./lib/statsd/instrument/rubocop/metric_value_keyword_argument.rb
  - ./lib/statsd/instrument/rubocop/positional_arguments.rb
  - ./lib/statsd/instrument/rubocop/splat_arguments.rb

AllCops:
  TargetRubyVersion: 2.3
  UseCache: true
  CacheRootDirectory: tmp/rubocop
  Exclude:
    - statsd-instrument.gemspec

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/statsd-instrument.rb

Style/ClassAndModuleChildren:
  Enabled: false # TODO: enable later


Style/MethodCallWithArgsParentheses:
  Enabled: false # TODO: enable later

# Enable our own cops on our own repos

StatsD/MetricReturnValue:
  Enabled: true

StatsD/MetricValueKeywordArgument:
  Enabled: true

StatsD/PositionalArguments:
  Enabled: true

StatsD/SplatArguments:
  Enabled: true
